spring.application.name= Journal app 

spring.data.mongodb.host = localhost
spring.data.mongodb.port = 27017
spring.data.mongodb.database = Journal_DB

# spring.data.mongodb.username = 
# spring.data.mongodb.password =s